### ISSUE TITLE
Change weight from category to content in structure view

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#128]
Especially when consecutive categories are identical, the bold face seems redundant. Maybe emphasize content? Or categories only in grey?

**Comment by sbruemmer** [comment]
[Example](http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2/gsa_391098.xml&page=1&view=structure)

I will test two solution: **change all labels** or **change just indented labels**

**Comment by sbruemmer** [comment]
I won't agree to emphasize content, because we style reading text througout the website identically.

Attached there are the two options. I do prefer option 3, because labels in the first level (not indented) are a stronger visual anchor if they are bold.

(Option 1) All labels grey:

![labels-grey](https://cloud.githubusercontent.com/assets/13978063/16151039/0686940e-349b-11e6-92fc-5394c3c1df8e.png)

(Option 2) Indented labels grey:

![indented-labels-grey](https://cloud.githubusercontent.com/assets/13978063/16151038/0685f33c-349b-11e6-96e2-403f018fb5a4.png)

(Option 3) Indented labels grey and not bold:

![indented-labels-grey-normal](https://cloud.githubusercontent.com/assets/13978063/16151040/06869878-349b-11e6-82bd-e25fa2c3c460.png)

**Comment by thvitt** [comment]
I'm against de-emphasizing the field labels. Especially when there are consecutive fields that don't fit on one line each the field labels serve as a kind of heading, separating the individual fields, cf the screenshot from _2 H_:

![Excerpt from 2 H's metadata](https://cloud.githubusercontent.com/assets/1906208/16553470/2ad258b2-41c9-11e6-9d39-316bf013f7ac.png)

If we deemphasize the labels we'll probably need a different visual clue here, like hanging indent or larger inter-field vertical space, which both lead to less information fitting on the screen.

**Comment by gerritbruening** [comment]
OK, that's a point. The issue is on the agenda of upcoming f2f meeting.

**Comment by thvitt** [comment]
The attempts to change emphasis here all decrease consistency or usability, so it's preferrable to leave it as it is now.
