### ISSUE TITLE
Please review spacings

### ISSUE THREAD

**Issue by sbruemmer** [faustedition/faust-web#141]
I have adjusted some print view spacings and alignments. Please review and let's discuss the changes marked below:

![print views](https://cloud.githubusercontent.com/assets/13978063/16226223/b45b9f72-37aa-11e6-8e62-3e52c3a0b369.JPG)

**Comment by gerritbruening** [comment]
Clearly preferable from my point of view.
The only thing I am not sure about is the interruption of the side bar after line 4620 (… Unglücksmann). @thvitt , what do you think?

**Comment by sbruemmer** [comment]
I did assume these spaces are between pages. The space was already there but it was an inner space so the border on the right wasn't interrupted but longer below the line than above. IMHO the space of variants boxes above and below every line should be equal.

**Comment by thvitt** [comment]
I would regard the bar/background color as (more or less) continuous information about the development of the variance/"Belegdichte" in the text. If there are white gaps in between, I would expect that this rather draws attention / suggests a gap in the data (e.g., text that has no variance or is only present in one witness), so I'd prefer continuous coloring over equal box heights.

**Comment by gerritbruening** [comment]
Agree to https://github.com/faustedition/faust-web/issues/141#issuecomment-227713707.

**Comment by gerritbruening** [comment]
@thvitt , what do you mean by "equal box heights"? Are the unequal ones to be treated differently?

**Comment by thvitt** [comment]
1. headings etc. are higher than normal verses since there is a margin above.

2. (more important) when there is a `<lg>`, there should be additional space before or after the line group. There are two ways to solve this: 

   a) in the beta, the first line of a `<lg>` has additional padding above (or the last line below, I don't remember), thus making the box higher. This leads to a larger (shaded) background area for this line and also a higher right border. 

   b) After @sbruemmer's modification, the additional vertical space is _outside_ of the box, thus background and border have the same height for all lines, but the additional vertical space will neither be shaded nor have a border, i.e. when the lines above and below the vertical space are shaded / have a border, there will be a visual white interruption of the shading.

   Neither solution is perfect, but especially in areas with many variants and witnesses I would consider (b) to over-emphasize the vertical space, suggesting that there happens something with relevance to the semantics of the shading/border (= #variants resp. #witnesses)

**Comment by gerritbruening** [comment]
I.e., a continuous border is wanted.
