### ISSUE TITLE
Preserve long ſ in textuelle Transkription

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#207]
Only in the "letzte abhebbare Stufe" the ſ is replaced by s.

See, for example, http://beta.faustedition.net/documentViewer?faustUri=faust://xml/document/faust/2.3/gsa_389949.xml&page=1&view=text.

**Comment by thvitt** [comment]
first bad commit: https://github.com/faustedition/faust-gen-html/commit/cfa1a7b5b41ef4a3df6e8db4bd0b0080a939755b New splitting based on section association in add-metadata.xsl

**Comment by thvitt** [comment]
The ſ→s conversion is already in the target/search subtree, which is the basis for the other steps.

Basically, that means:

1. removal of the character normalization from the addMetadata stuff
2. check whether ſ are a problem for the search. If so, investigate ways around.
   The problem is that we need the search/ xml content for both full-text retrieval and search results display. So if its a problem, and if we can't configure the lucene analyzer accordingly, we'll probably have to accept s in the search rults (or implement something complex).

**Comment by thvitt** [comment]
@gerritbruening, sollen denn die übrigen Zeichennormalisierungen im Einblendungsapparat angewandt werden?

	ā → aa
	ē → ee
	m̄ → mm
	n̄ → nn
	r̄ → rr
	ſs → ß
	— → –

	<xsl:template match="orig/text()[. = 'sſ']">ß</xsl:template>

**Comment by gerritbruening** [comment]
Nach momentan gültigen Prinzipien soll das alles immer erst bei der letzten Stufe geschehen:

><h3>Darstellung der letzten abhebbaren Stufe</h3>
><p>Die letzte abhebbare Stufe ist der Text, der sich aus der Niederschrift und allen darin
>            vorkommenden Änderungen ergibt. Für die Darstellung dieses Textes gelten folgende
>            besonderen Regeln:</p>
>        <ul>
>           <li>Das lange s (ſ) wird als rundes s wiedergegeben. Die Buchstabenkombination ſs in der
>                lateinischen Schrift wird als ß wiedergegeben.</li>
>            <li>Geminationsstriche über n und m (n̄, m̄) und weiteren Buchstaben werden zu nn, mm
>                usw. aufgelöst.</li>
>        </ul>

http://dev.faustedition.net/transcription_guidelines#txt_Transkr_Hss

**Comment by thvitt** [comment]
Also irgendwas fehlt noch …

**Comment by thvitt** [comment]
Other problem is that `emend-core.xsl` rules (at least text()) apply in `apparatus.xml`, which they shouldn't.
