### ISSUE TITLE
Testimonies: Sorting of Druckort column broken

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-web#240]
In the testimonies table, the sorting by "Druckort" is not working properly. The results of the sorting are rather random.
Additionally I think the sorting by name should be sorted by lastname instead of first name, this would bring more efficent results.

**Comment by thvitt** [comment]
_Druckort_ is sorted using the _bibliography_ sort method (originally developped for the bibliography keys) which splits each entry into a sequence of consecutive non-digit (α) and digits-only (δ) substrings, α₁δ₂α₃δ₄α₅, using the RE
```javascript
var BIB        = /^(\D+)(\d+)(\D+)(\d+)(\D+)/;
```
 Everything after α₅ is ignored.

The first (slightly) broken entries I could see on a cursory glance are the WA entries. E.g., in `WA I, 5 (1), 244` we have α₁ = `WA I, `, δ₂ = `5`, α₃ = ` (`, δ₄ = `1`, α₅ = `), ` which is the same as for `WA I, 5 (1), 102`. 

The WA entries (`WA IV, 43, 81, 85; WA I, 15 (2), 126 (Beilage)`) are mysteriously interrupted by `Wagner 1838, S. 53f.` (and a bunch of entries following that), which is surprising since `WA IV, ` < `Wagner` using localeCompare‽ Things get very strange afterwards, I'd guess sorting simply stops somewhere there.

@gerritbruening, is the _Druckort_ column to stay in the table in this format (after we included the actual testimonies in the edition)?

**Comment by gerritbruening** [comment]
Yes, we could suppress column Druckort in the future. Right now it would be helpful, because it helps us to group testimonies which occur in one and the same WA volume. This directs us to the corresponding Zeno data.
