### ISSUE TITLE
Print page numbers misrendered

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#244]
For example, [B9, page 36](http://dev.faustedition.net/print/B9_IIIB20-2.4#dt44) is rendered as page 44. The tooltip shows the correct text "36".

**Comment by gerritbruening** [comment]
It seems as if just the `pb` were counted, see for example http://dev.faustedition.net/print/C(1)4_IIIB24.

**Comment by thvitt** [comment]
It's underspecified, actually.

For the manuscripts, the document viewer requires a page number that is a continuos arabic number starting at 1 to reference the individual page of a manuscript page. This page number is used for navigation etc. in the pager, and we also display it in the textual transcripts for consistency reasons. This number (called `@f:docTranscriptNo`) is the position of the `<page>` element that corresponds to `pb/@n` in the metadata document. Now, the tooltip shows the actual value of `@n`, the normalized number is displayed.

When we integrate the prints' facsimiles, we should be as consistent as possible for the UI of the documentViewer, so we'll also use normalized numbers. Since there are no `<page>` elements, we simply count the `<pb>`s, and since we use the same stylesheets, this is what is displayed for page number.

Feel free to copy/edit the table (which shows the status quo) to express your wishes:

| Feature                                    | Manuscript                                     | Print                                |
|--------------------------------------------|------------------------------------------------|--------------------------------------|
| Used in Pager, URL                         | `@f:docTranscriptNo`, pos. of `<page>` element | `@f:docTranscriptNo`, pos. of `<pb>` |
| Displayed in textual transcript for `<pb>` | `@f:docTranscriptNo`                           | `@f:docTranscriptNo`                  |
| Transcript `<pb>` tooltip                  | `@n`                                           | `@n`                                 |

**Comment by gerritbruening** [comment]
The problem is that we do not always represent complete printed volumes, but also only parts of them. The structure then is:
* front matter
* text
* (maybe another text)
* back matter
A page numbering that simply counts existing `pb`s works but is not nice if it is the only page numbering. Can we have this page numbering and an aditional one based on `pb/@n`?

**Comment by thvitt** [comment]
In the textual transcripts, we can display whatever page number you wish (if we can calculate it at that point). For the pager and the URLs (only relevant when the prints' facsimiles have been included) we need continuous, unique decimal numbers, although, as for the manuscripts, individual pages may be missing.

**Comment by gerritbruening** [comment]
OK thanks, agree!

**Comment by gerritbruening** [comment]
I have edited the table in https://github.com/faustedition/faust-web/issues/244#issuecomment-274501024.

What I would like to have here:
http://dev.faustedition.net/print/A8_IIIB18.all#lbefore_1_a
is "1" in the display of the `pb`, not only in the tooltip.

If there is a reason why "9" is indispensable here, for example, because it corresponds to the pager, we could display something like "1 [9]".
Does that help in defining a task?
