### ISSUE TITLE
Some testimonies are witnesses; link them to documents

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#259]
E.g., Pniower 931 is identical to 2 III H.40.

Additionally, link witnesses in the document viewer to testimony metadata entries.

@thvitt , do you want us to do this in the `xls` or better somewhere else?

**Comment by thvitt** [comment]
Depends on what should happen there. If simply a link to the standard document viewer representation is required, a column in the excel table is probably easiest.

**Comment by gerritbruening** [comment]
Yes, we simply need a link to the document viewer.

@sandrakrause , könnten Sie eine Spalte namens Faust-Dokument oder so in der Excel-Datei hinzufügen und dort die Sigle eintragen? Die betreffenden "Zeugnisse" sind daran erkennbar, dass als Druckort "WA I, 14" oder "WA I, 15" angegeben ist.

**Comment by thvitt** [comment]
Fixed in https://github.com/faustedition/faust-gen-html/commit/6a93f40e5f4bb35f7ca9077bb399d07eea785bcf 

@dietmarpravida, @sandrakrause, es gibt noch ein paar defekte Links (d.h. nicht existierende oder falschgeschriebene Siglen in der Exceltabelle, [z.B. bei Pniower 945](http://dev.digital-humanities.de/archive_testimonies#pniower_945). Außerdem muss noch entschieden werden:
* was in Fällen geschehen soll, in denen ein `<milestone unit="testimony"/>` unter testimonies/ _und_ eine H-Sigle vorhanden ist, z.B. [Gräf 1270](http://dev.digital-humanities.de/archive_testimonies#graef_1270)
* ob/wie/wo für Einträge, die _nur_ Siglen haben, die Metadaten aus der Excel-Tabelle (#269) gerendert und verlinkt werden sollen
