### ISSUE TITLE
document-viewer shows empty pages in older firefox-versions

### ISSUE THREAD

**Issue by sandrakrause** [faustedition/faust-web#409]
When opening transcripts or prints with an older version of firefox
it shows only blank pages and all actions taken don't result in anything (e.g. turning page, changing view --> nothing happens)
Problem appeared in seminar and I could reproduce it on my laptop with Firefox 47.0.1.
I don't know about the behaviour of older versions of other browsers.

Is it possible to
a. support older versions or
b. integrate an error message of some kind (so that it is as least understandable why nothing is happening?)

**Comment by thvitt** [comment]
Currently, the dev version is only tested with current versions of Firefox and Chrome.

a. I don’t see much reason in putting much effort in supporting older browser versions, although we should define some criteria and perform tests for what we really support. My suggestion would be the latest ESR releases of Firefox/Chrome and maybe current Edge

b. 990bb4575e4b51d035f00007b23862c89344437b introduces an error message when the document viewer fails to load due to some error that falls through (e.g., javascript errors), 543232fb9e3a1cf976f27e0dcf20c4721c330226 provides additional details for error reporting.

**Comment by thvitt** [comment]
we’ve an error message now, and decision has been to support the last ESR version.
