### ISSUE TITLE
archive_locations: enable sorting?

### ISSUE THREAD

**Issue by gerritbruening** [faustedition/faust-web#94]
E.g., by the amout of witnesses or pages.

**Comment by thvitt** [comment]
Table from #134 also needs sorting.

Sorting in the only table that currently supports sorting – the manuscript table – is implemented in a rather unportable way, by performing a specific sort on the source data and then regenerating the table.

It is probably better to work on the actual table data by associating global stuff (sort method, etc.) to the `<th>` and perform the actual sort based on the `<td>` elements. We can probably just use an existing table sorting library, or implement something along these lines, instead of re-implementing the data-based sorting for every table.

**Comment by thvitt** [comment]
https://github.com/HubSpot/sortable looks good, it allows us to drop in the sigil sort stuff, supports sorting by supplied data attribute and doesn't bring in any dependencies.

So I guess it's just using bringing this in, ditching the sort-data-first approach, and adjusting all tables slightly so they are picked up by _sortable_.

**Comment by gerritbruening** [comment]
OK, sounds like a very good idea!
